=== dlocquiao/4850Lab07/application/data/Term.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Vithusan
Derrick
-->



<!-- The term defines the dayOfWeek, period, course  -->
<!ELEMENT WinterTerm (dayOfWeek, period, course, instructor, room)>
<!ELEMENT course (#PCDATA)>
<!ATTLIST course number (4620|4650|4660|4770|4850|4910) #REQUIRED  >
<!ELEMENT room (#PCDATA)>
<!-- Periods can begin at 8:30, 9:30, 10:30, 11:30, 12:30, 13:30, 14:30, 15:30, 16:30  -->
<!ELEMENT period (#PCDATA)>
<!ATTLIST period time (830|930|1030|1130|1230|1330|1430|1530|1630) #REQUIRED  >
<!ELEMENT dayOfWeek (#PCDATA)>
<!-- Days for classes are monday, tuesday, wednesday, thursday, or friday -->
<!ATTLIST dayOfWeek day (mon|tues|weds|thurs|fri) #REQUIRED  >
<!ELEMENT instructor (#PCDATA)>

=== dlocquiao/4850Lab07/application/data/timetable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE WinterTerm SYSTEM 'Term.dtd'>

<WinterTerm>
    <dayOfWeek day="monday">
        <period time="10:30">
            <course number="4650">
                <room>SE12-306</room>
                <instructor>Medhat Elmasry</instructor>
            </course>        
        </period>
        <period time="15:30">
            <course number="4910">
                <room>SW9-206</room>
                <instructor>Richard Chau</instructor>
            </course>        
        </period>
        <period time="16:30">
            <course number="4650">
                <room>SE6-205</room>
                <instructor>Medhat Elmasry</instructor>
            </course>        
        </period>
    </dayOfWeek>
    <dayOfWeek day="tuesday">
        <period time="8:30">
            <course number="4620">
                <room>SE12-306</room>
                <instructor>Bethany Edmunds</instructor>
            </course>        
        </period>
        <period time="12:30">
            <course number="4650">
                <room>SW9-206</room>
                <instructor>Medhat Elmasry</instructor>
            </course>        
        </period>
        <period time="15:30">
            <course number="4620">
                <room>SW3-3615</room>
                <instructor>Bethany Edmunds</instructor>
            </course>        
        </period>
    </dayOfWeek>
    <dayOfWeek day="thursday">
        <period time="9:30">
            <course number="4910">
                <room>SW5-1840</room>
                <instructor>Richard Chau</instructor>
            </course>        
        </period>
        <period time="10:30">
            <course number="4910">
                <room>SE12-306</room>
                <instructor>Richard Chau</instructor>
            </course>        
        </period>
        <period time="13:30">
            <course number="4850">
                <room>SE12-308</room>
                <instructor>James Parry</instructor>
            </course>        
        </period>
    </dayOfWeek>
    <dayOfWeek day="friday">
        <period time="8:30">
            <course number="4660">
                <room>SW9-206</room>
                <instructor>Steve Fabiszewski</instructor>
            </course>        
        </period>
        <period time="10:30">
            <course number="4770">
                <room>SE12_306</room>
                <instructor>Trevor Lord</instructor>
            </course>        
        </period>
        <period time="13:30">
            <course number="4660">
                <room>SE12-306</room>
                <instructor>Steve Fabiszewski</instructor>
            </course>        
        </period>
    </dayOfWeek>
</WinterTerm>
